apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris
  namespace: seldon
spec:
  predictors:
    - name: default
      graph:
        implementation: STO_SERVER
        modelUri: azureblob:testig/testdata
        name: classifier
        storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
        envSecretRefName: secret
        parameters:
          - name: method
            type: STRING
            value: predict
      replicas: 3
